//====================================================================================================
// Base code generated with LeatherGoods - ASF.Data
// Architecture Solutions Foundation
//
// Generated by academic at LeatherGoods V 1.0 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Data.Common;
using System.Data;
using Microsoft.Practices.EnterpriseLibrary.Data;
using ASF.Entities;

namespace ASF.Data
{
    /// <summary>
    /// 
    /// </summary>
    public class CartItemDac : DataAccessComponent
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="cartItem"></param>
        /// <returns></returns>
        public CartItem Create(CartItem cartItem)
        {
            const string sqlStatement = "INSERT INTO dbo.CartItem ([CartId], [Price], [ProductId], [Quantity], [CreatedOn], [CreatedBy], [ChangedOn], [ChangedBy]) " +
                "VALUES(@CartId, @Price, @ProductId, @Quantity, @CreatedOn, @CreatedBy, @ChangedOn, @ChangedBy); SELECT SCOPE_IDENTITY();";

            var db = DatabaseFactory.CreateDatabase(ConnectionName);
            using (var cmd = db.GetSqlStringCommand(sqlStatement))
            {
                db.AddInParameter(cmd, "@CartId", DbType.Int32, cartItem.CartId);
                db.AddInParameter(cmd, "@Price", DbType.Decimal, cartItem.Price);
                db.AddInParameter(cmd, "@ProductId", DbType.Int32, cartItem.ProductId);
                db.AddInParameter(cmd, "@Quantity", DbType.Int32, cartItem.Quantity);
                db.AddInParameter(cmd, "@CreatedOn", DbType.DateTime2, DateTime.Now);
                db.AddInParameter(cmd, "@CreatedBy", DbType.Int32, cartItem.CreatedBy);
                db.AddInParameter(cmd, "@ChangedOn", DbType.DateTime2, DateTime.Now);
                db.AddInParameter(cmd, "@ChangedBy", DbType.Int32, cartItem.ChangedBy);
                // Obtener el valor de la primary key.
                cartItem.Id = Convert.ToInt32(db.ExecuteScalar(cmd));
            }

            return cartItem;
        }

        public List<CartItem> SelectByCartId(int cartId)
        {
            const string sqlStatement = "SELECT [Id], [CartId], [Price], [ProductId], [Quantity], [CreatedOn], [CreatedBy], [ChangedOn], [ChangedBy] FROM dbo.CartItem " +
                "WHERE CartId=@CartId";

            var result = new List<CartItem>();
            var db = DatabaseFactory.CreateDatabase(ConnectionName);
            using (var cmd = db.GetSqlStringCommand(sqlStatement))
            {

                db.AddInParameter(cmd, "@CartId", DbType.Int32, cartId);
                using (var dr = db.ExecuteReader(cmd))
                {
                    while (dr.Read())
                    {
                        var cartItem = LoadCartItem(dr); // Mapper
                        result.Add(cartItem);
                    }
                }
            }

            return result;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="cartItem"></param>
        public void UpdateById(CartItem cartItem)
        {
            const string sqlStatement = "UPDATE dbo.CartItem " +
                "SET [CartId]=@CartId, " +
                    "[Price]=@Price, " +
                    "[ProductId]=@ProductId, " +
                    "[Quantity]=@Quantity, " +
                    "[CreatedOn]=@CreatedOn, " +
                    "[CreatedBy]=@CreatedBy, " +
                    "[ChangedOn]=@ChangedOn, " +
                    "[ChangedBy]=@ChangedBy " +
                "WHERE [Id]=@Id ";

            var db = DatabaseFactory.CreateDatabase(ConnectionName);
            using (var cmd = db.GetSqlStringCommand(sqlStatement))
            {
                db.AddInParameter(cmd, "@CartId", DbType.Int32, cartItem.CartId);
                db.AddInParameter(cmd, "@Price", DbType.Decimal, cartItem.Price);
                db.AddInParameter(cmd, "@ProductId", DbType.Int32, cartItem.ProductId);
                db.AddInParameter(cmd, "@Quantity", DbType.Int32, cartItem.Quantity);
                db.AddInParameter(cmd, "@CreatedOn", DbType.DateTime2, cartItem.CreatedOn);
                db.AddInParameter(cmd, "@CreatedBy", DbType.Int32, cartItem.CreatedBy);
                db.AddInParameter(cmd, "@ChangedOn", DbType.DateTime2, cartItem.ChangedOn);
                db.AddInParameter(cmd, "@ChangedBy", DbType.Int32, cartItem.ChangedBy);
                db.AddInParameter(cmd, "@Id", DbType.Int32, cartItem.Id);

                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        public void DeleteById(int id)
        {
            const string sqlStatement = "DELETE dbo.CartItem WHERE [Id]=@Id ";
            var db = DatabaseFactory.CreateDatabase(ConnectionName);
            using (var cmd = db.GetSqlStringCommand(sqlStatement))
            {
                db.AddInParameter(cmd, "@Id", DbType.Int32, id);
                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public CartItem SelectById(int id)
        {
            const string sqlStatement = "SELECT [Id], [CartId], [Price], [ProductId], [Quantity], [CreatedOn], [CreatedBy], [ChangedOn], [ChangedBy] " +
                "FROM dbo.CartItem WHERE [Id]=@Id ";

            CartItem cartItem = null;
            var db = DatabaseFactory.CreateDatabase(ConnectionName);
            using (var cmd = db.GetSqlStringCommand(sqlStatement))
            {
                db.AddInParameter(cmd, "@Id", DbType.Int32, id);
                using (var dr = db.ExecuteReader(cmd))
                {
                    if (dr.Read()) cartItem = LoadCartItem(dr);
                }
            }

            return cartItem;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>		
        public List<CartItem> Select()
        {
            // WARNING! Performance
            const string sqlStatement = "SELECT [Id], [CartId], [Price], [ProductId], [Quantity], [CreatedOn], [CreatedBy], [ChangedOn], [ChangedBy] FROM dbo.CartItem ";

            var result = new List<CartItem>();
            var db = DatabaseFactory.CreateDatabase(ConnectionName);
            using (var cmd = db.GetSqlStringCommand(sqlStatement))
            {
                using (var dr = db.ExecuteReader(cmd))
                {
                    while (dr.Read())
                    {
                        var cartItem = LoadCartItem(dr); // Mapper
                        result.Add(cartItem);
                    }
                }
            }

            return result;
        }
        
        private static CartItem LoadCartItem(IDataReader dr)
        {
            var cartItem = new CartItem
            {
                Id = GetDataValue<int>(dr, "Id"),
                CartId = GetDataValue<int>(dr, "CartId"),
                Price = GetDataValue<double>(dr, "Price"),
                ProductId = GetDataValue<int>(dr, "ProductId"),
                Quantity = GetDataValue<int>(dr, "Quantity"),
                CreatedOn = GetDataValue<DateTime>(dr, "CreatedOn"),
                CreatedBy = GetDataValue<int>(dr, "CreatedBy"),
                ChangedOn = GetDataValue<DateTime>(dr, "ChangedOn"),
                ChangedBy = GetDataValue<int>(dr, "ChangedBy")
            };
            return cartItem;
        }
    }
}

