//====================================================================================================
// Base code generated with LeatherGoods - ASF.Data
// Architecture Solutions Foundation
//
// Generated by academic at LeatherGoods V 1.0 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Data.Common;
using System.Data;
using Microsoft.Practices.EnterpriseLibrary.Data;
using ASF.Entities;

namespace ASF.Data
{
    /// <summary>
    /// 
    /// </summary>
    public class OrderDetailDac : DataAccessComponent
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="orderDetail"></param>
        /// <returns></returns>
        public OrderDetail Create(OrderDetail orderDetail)
        {
            const string sqlStatement = "INSERT INTO dbo.OrderDetail ([OrderId], [Price], [ProductId], [Quantity], [CreatedOn], [CreatedBy], [ChangedOn], [ChangedBy]) " +
                "VALUES(@OrderId, @Price, @ProductId, @Quantity, @CreatedOn, @CreatedBy, @ChangedOn, @ChangedBy); SELECT SCOPE_IDENTITY();";

            var db = DatabaseFactory.CreateDatabase(ConnectionName);
            using (var cmd = db.GetSqlStringCommand(sqlStatement))
            {
                db.AddInParameter(cmd, "@OrderId", DbType.Int32, orderDetail.OrderId);
                db.AddInParameter(cmd, "@Price", DbType.Decimal, orderDetail.Price);
                db.AddInParameter(cmd, "@ProductId", DbType.Int32, orderDetail.ProductId);
                db.AddInParameter(cmd, "@Quantity", DbType.Int32, orderDetail.Quantity);
                db.AddInParameter(cmd, "@CreatedOn", DbType.DateTime2, DateTime.Now);
                db.AddInParameter(cmd, "@CreatedBy", DbType.Int32, orderDetail.CreatedBy);
                db.AddInParameter(cmd, "@ChangedOn", DbType.DateTime2, DateTime.Now);
                db.AddInParameter(cmd, "@ChangedBy", DbType.Int32, orderDetail.ChangedBy);
                // Obtener el valor de la primary key.
                orderDetail.Id = Convert.ToInt32(db.ExecuteScalar(cmd));
            }

            return orderDetail;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="orderDetail"></param>
        public void UpdateById(OrderDetail orderDetail)
        {
            const string sqlStatement = "UPDATE dbo.OrderDetail " +
                "SET [OrderId]=@OrderId, " +
                    "[Price]=@Price, " +
                    "[ProductId]=@ProductId, " +
                    "[Quantity]=@Quantity, " +
                    "[CreatedOn]=@CreatedOn, " +
                    "[CreatedBy]=@CreatedBy, " +
                    "[ChangedOn]=@ChangedOn, " +
                    "[ChangedBy]=@ChangedBy " +
                "WHERE [Id]=@Id ";

            var db = DatabaseFactory.CreateDatabase(ConnectionName);
            using (var cmd = db.GetSqlStringCommand(sqlStatement))
            {
                db.AddInParameter(cmd, "@OrderId", DbType.Int32, orderDetail.OrderId);
                db.AddInParameter(cmd, "@Price", DbType.Decimal, orderDetail.Price);
                db.AddInParameter(cmd, "@ProductId", DbType.Int32, orderDetail.ProductId);
                db.AddInParameter(cmd, "@Quantity", DbType.Int32, orderDetail.Quantity);
                db.AddInParameter(cmd, "@CreatedOn", DbType.DateTime2, orderDetail.CreatedOn);
                db.AddInParameter(cmd, "@CreatedBy", DbType.Int32, orderDetail.CreatedBy);
                db.AddInParameter(cmd, "@ChangedOn", DbType.DateTime2, orderDetail.ChangedOn);
                db.AddInParameter(cmd, "@ChangedBy", DbType.Int32, orderDetail.ChangedBy);
                db.AddInParameter(cmd, "@Id", DbType.Int32, orderDetail.Id);

                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        public void DeleteById(int id)
        {
            const string sqlStatement = "DELETE dbo.OrderDetail WHERE [Id]=@Id ";
            var db = DatabaseFactory.CreateDatabase(ConnectionName);
            using (var cmd = db.GetSqlStringCommand(sqlStatement))
            {
                db.AddInParameter(cmd, "@Id", DbType.Int32, id);
                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public OrderDetail SelectById(int id)
        {
            const string sqlStatement = "SELECT [Id], [OrderId], [Price], [ProductId], [Quantity], [CreatedOn], [CreatedBy], [ChangedOn], [ChangedBy] " +
                "FROM dbo.OrderDetail WHERE [Id]=@Id ";

            OrderDetail orderDetail = null;
            var db = DatabaseFactory.CreateDatabase(ConnectionName);
            using (var cmd = db.GetSqlStringCommand(sqlStatement))
            {
                db.AddInParameter(cmd, "@Id", DbType.Int32, id);
                using (var dr = db.ExecuteReader(cmd))
                {
                    if (dr.Read()) orderDetail = LoadOrderDetail(dr);
                }
            }

            return orderDetail;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>		
        public List<OrderDetail> Select()
        {
            // WARNING! Performance
            const string sqlStatement = "SELECT [Id], [OrderId], [Price], [ProductId], [Quantity], [CreatedOn], [CreatedBy], [ChangedOn], [ChangedBy] FROM dbo.OrderDetail ";

            var result = new List<OrderDetail>();
            var db = DatabaseFactory.CreateDatabase(ConnectionName);
            using (var cmd = db.GetSqlStringCommand(sqlStatement))
            {
                using (var dr = db.ExecuteReader(cmd))
                {
                    while (dr.Read())
                    {
                        var orderDetail = LoadOrderDetail(dr); // Mapper
                        result.Add(orderDetail);
                    }
                }
            }

            return result;
        }

        public List<OrderDetail> SelectByOrderId(int id)
        {
            // WARNING! Performance
            const string sqlStatement = "SELECT [Id], [OrderId], [Price], [ProductId], [Quantity], [CreatedOn], [CreatedBy], [ChangedOn], [ChangedBy] FROM dbo.OrderDetail" +
                "Where OrderId=@Id ";

            var result = new List<OrderDetail>();
            var db = DatabaseFactory.CreateDatabase(ConnectionName);
            using (var cmd = db.GetSqlStringCommand(sqlStatement))
            {
                db.AddInParameter(cmd, "@Id", DbType.Int32, id);
                using (var dr = db.ExecuteReader(cmd))
                {
                    while (dr.Read())
                    {
                        var orderDetail = LoadOrderDetail(dr); // Mapper
                        result.Add(orderDetail);
                    }
                }
            }

            return result;
        }

        private static OrderDetail LoadOrderDetail(IDataReader dr)
        {
            var orderDetail = new OrderDetail
            {
                Id = GetDataValue<int>(dr, "Id"),
                OrderId = GetDataValue<int>(dr, "OrderId"),
                Price = GetDataValue<double>(dr, "Price"),
                ProductId = GetDataValue<int>(dr, "ProductId"),
                Quantity = GetDataValue<int>(dr, "Quantity"),
                CreatedOn = GetDataValue<DateTime>(dr, "CreatedOn"),
                CreatedBy = GetDataValue<int>(dr, "CreatedBy"),
                ChangedOn = GetDataValue<DateTime>(dr, "ChangedOn"),
                ChangedBy = GetDataValue<int>(dr, "ChangedBy")
            };
            return orderDetail;
        }
    }
}

