//====================================================================================================
// Base code generated with LeatherGoods - ASF.Data
// Architecture Solutions Foundation
//
// Generated by academic at LeatherGoods V 1.0 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Data.Common;
using System.Data;
using Microsoft.Practices.EnterpriseLibrary.Data;
using ASF.Entities;

namespace ASF.Data
{
    /// <summary>
    /// 
    /// </summary>
    public class ProductDac : DataAccessComponent
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="product"></param>
        /// <returns></returns>
        public Product Create(Product product)
        {
            const string sqlStatement = @"INSERT INTO dbo.Product ([AvgStars], [DealerId], [Description], [Image], [Price], [QuantitySold], [Title], 
                [CreatedOn], [CreatedBy], [ChangedOn], [ChangedBy])
                VALUES(@AvgStars, @DealerId, @Description, @Image, @Price, @QuantitySold, @Title, @CreatedOn, @CreatedBy, @ChangedOn, @ChangedBy); SELECT SCOPE_IDENTITY();";

            var db = DatabaseFactory.CreateDatabase(ConnectionName);
            using (var cmd = db.GetSqlStringCommand(sqlStatement))
            {
                db.AddInParameter(cmd, "@AvgStars", DbType.Decimal, 0);
                db.AddInParameter(cmd, "@DealerId", DbType.Int32, product.DealerId);
                db.AddInParameter(cmd, "@Description", DbType.String, product.Description);
                db.AddInParameter(cmd, "@Image", DbType.String, product.Image);
                db.AddInParameter(cmd, "@Price", DbType.Decimal, product.Price);
                db.AddInParameter(cmd, "@QuantitySold", DbType.Int32, 0);
                db.AddInParameter(cmd, "@Title", DbType.String, product.Title);
                db.AddInParameter(cmd, "@CreatedOn", DbType.DateTime2, DateTime.Now);
                db.AddInParameter(cmd, "@CreatedBy", DbType.Int32, product.CreatedBy);
                db.AddInParameter(cmd, "@ChangedOn", DbType.DateTime2, DateTime.Now);
                db.AddInParameter(cmd, "@ChangedBy", DbType.Int32, product.ChangedBy);
                // Obtener el valor de la primary key.
                product.Id = Convert.ToInt32(db.ExecuteScalar(cmd));
            }

            return product;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="product"></param>
        public void UpdateById(Product product)
        {
            const string sqlStatement = @"UPDATE dbo.Product 
                SET [AvgStars]=@AvgStars, 
                    [DealerId]=@DealerId, 
                    [Description]=@Description, 
                    [Image]=@Image, 
                    [Price]=@Price, 
                    [QuantitySold]=@QuantitySold, 
                    [Title]=@Title,
                    [ChangedOn]=@ChangedOn, 
                    [ChangedBy]=@ChangedBy 
                WHERE [Id]=@Id ";

            var db = DatabaseFactory.CreateDatabase(ConnectionName);
            using (var cmd = db.GetSqlStringCommand(sqlStatement))
            {
                db.AddInParameter(cmd, "@AvgStars", DbType.Decimal, product.AvgStars);
                db.AddInParameter(cmd, "@DealerId", DbType.Int32, product.DealerId);
                db.AddInParameter(cmd, "@Description", DbType.String, product.Description);
                db.AddInParameter(cmd, "@Image", DbType.String, product.Image);
                db.AddInParameter(cmd, "@Price", DbType.Decimal, product.Price);
                db.AddInParameter(cmd, "@QuantitySold", DbType.Int32, product.QuantitySold);
                db.AddInParameter(cmd, "@Title", DbType.String, product.Title);
                db.AddInParameter(cmd, "@ChangedOn", DbType.DateTime2, product.ChangedOn);
                db.AddInParameter(cmd, "@ChangedBy", DbType.Int32, product.ChangedBy);
                db.AddInParameter(cmd, "@Id", DbType.Int32, product.Id);

                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        public void DeleteById(int id)
        {
            const string sqlStatement = "DELETE dbo.Product WHERE [Id]=@Id ";
            var db = DatabaseFactory.CreateDatabase(ConnectionName);
            using (var cmd = db.GetSqlStringCommand(sqlStatement))
            {
                db.AddInParameter(cmd, "@Id", DbType.Int32, id);
                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public Product SelectById(int id)
        {
            const string sqlStatement = "SELECT [Id], [AvgStars], [DealerId], [Description], [Image], [Price], [QuantitySold], [Title], [CreatedOn], [CreatedBy], [ChangedOn], [ChangedBy] " +
                "FROM dbo.Product WHERE [Id]=@Id ";

            Product product = null;
            var db = DatabaseFactory.CreateDatabase(ConnectionName);
            using (var cmd = db.GetSqlStringCommand(sqlStatement))
            {
                db.AddInParameter(cmd, "@Id", DbType.Int32, id);
                using (var dr = db.ExecuteReader(cmd))
                {
                    if (dr.Read()) product = LoadProduct(dr);
                }
            }

            return product;
        }

        public List<Product> Select(int pageNumber, int pageSize)
        {
            const string sqlStatement = @"
                                        SELECT [Id], [AvgStars], [DealerId], [Description], [Image], [Price], [QuantitySold], [Title], [CreatedOn], [CreatedBy], [ChangedOn], [ChangedBy] 
                                        FROM dbo.Product ORDER BY Id OFFSET @Offset ROWS FETCH NEXT @PageSize ROWS ONLY;";

            var result = new List<Product>();
            var db = DatabaseFactory.CreateDatabase(ConnectionName);
            using (var cmd = db.GetSqlStringCommand(sqlStatement))
            {
                db.AddInParameter(cmd, "@Offset", DbType.Int32, (pageNumber - 1) * pageSize);
                db.AddInParameter(cmd, "@PageSize", DbType.Int32, pageSize);
                using (var dr = db.ExecuteReader(cmd))
                {
                    while (dr.Read())
                    {
                        var product = LoadProduct(dr); // Mapper
                        result.Add(product);
                    }
                }
            }

            return result;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>		
        public List<Product> SelectOrderByTitle(int pageNumber, int pageSize)
        {
            const string sqlStatement = @"
                                        SELECT [Id], [AvgStars], [DealerId], [Description], [Image], [Price], [QuantitySold], [Title], [CreatedOn], [CreatedBy], [ChangedOn], [ChangedBy] 
                                        FROM dbo.Product ORDER BY Title OFFSET @Offset ROWS FETCH NEXT @PageSize ROWS ONLY;";

            var result = new List<Product>();
            var db = DatabaseFactory.CreateDatabase(ConnectionName);
            using (var cmd = db.GetSqlStringCommand(sqlStatement))
            {
                db.AddInParameter(cmd, "@Offset", DbType.Int32, (pageNumber - 1) * pageSize);
                db.AddInParameter(cmd, "@PageSize", DbType.Int32, pageSize);
                using (var dr = db.ExecuteReader(cmd))
                {
                    while (dr.Read())
                    {
                        var product = LoadProduct(dr); // Mapper
                        result.Add(product);
                    }
                }
            }

            return result;
        }
        private static Product LoadProduct(IDataReader dr)
        {
            var product = new Product
            {
                Id = GetDataValue<int>(dr, "Id"),
                AvgStars = GetDataValue<double>(dr, "AvgStars"),
                DealerId = GetDataValue<int>(dr, "DealerId"),
                Description = GetDataValue<string>(dr, "Description"),
                Image = GetDataValue<string>(dr, "Image"),
                Price = GetDataValue<double>(dr, "Price"),
                QuantitySold = GetDataValue<int>(dr, "QuantitySold"),
                Title = GetDataValue<string>(dr, "Title"),
                CreatedOn = GetDataValue<DateTime>(dr, "CreatedOn"),
                CreatedBy = GetDataValue<int>(dr, "CreatedBy"),
                ChangedOn = GetDataValue<DateTime>(dr, "ChangedOn"),
                ChangedBy = GetDataValue<int>(dr, "ChangedBy")
            };
            return product;
        }
    }
}

