//====================================================================================================
// Base code generated with LeatherGoods - ASF.Business
// Architecture Solutions Foundation
//
// Generated by academic at LeatherGoods V 1.0 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using ASF.Entities;
using ASF.Data;


namespace ASF.Business
{
    /// <summary>
    /// CartItemBusiness business component.
    /// </summary>
    public class CartItemBusiness
    {
        /// <summary>
        /// Add method. 
        /// </summary>
        /// <param name="cartItem"></param>
        /// <returns></returns>
        public CartItem Add(CartItem cartItem)
        {
            var cartItemDac = new CartItemDac();
            var cartDac = new CartDac();

            List<CartItem> cart = cartItemDac.SelectByCartId(cartItem.CartId);
            CartItem search = cart.Find(x => x.ProductId == cartItem.ProductId);
            if (search == default(CartItem))
            {
                return cartItemDac.Create(cartItem);
            }

            search.Quantity = search.Quantity + cartItem.Quantity;
            search.Price = cartItem.Price;

            return search;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        public void Remove(int id)
        {
            var cartItemDac = new CartItemDac();
            cartItemDac.DeleteById(id);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public List<CartItem> All()
        {
            var cartItemDac = new CartItemDac();
            var result = cartItemDac.Select();
            return result;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public CartItem Find(int id)
        {
            var cartItemDac = new CartItemDac();
            var result = cartItemDac.SelectById(id);
            return result;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="cartItem"></param>
        public void Edit(CartItem cartItem)
        {
            var cartItemDac = new CartItemDac();
            cartItemDac.UpdateById(cartItem);
        }

        public List<CartItem> AllByCart(int cartId)
        {
            var cartItemDac = new CartItemDac();
            var result = cartItemDac.SelectByCartId(cartId);
            return result;
        }
    }
}
